import { IMAGES } from "./images";
import { WifiList } from "@/types/wifi.types";

export const WIFI_LIST: WifiList[] = [
  {
    id: 1,
    mainImage: IMAGES.list1Iamge,
    title: "한 달 120GB",
    price: "49,800원",
    salePrice: "130,000원",
    saleImage: IMAGES.saleIamge,
    mdImage: IMAGES.mdImage,
    name: "그리핀 120",
    info: "4G/LTE",
    rental: "한 달 단위 대여",
    heart: 0,
  },
  {
    id: 2,
    mainImage: IMAGES.list2Iamge,
    title: "속도저하 없는 초고속 무제한",
    price: "84,900원",
    salePrice: "130,000원",
    saleImage: IMAGES.saleIamge,
    name: "하트여왕 슈퍼MAX",
    info: "4G/LTE 최대 50Mbps",
    rental: "한 달 단위 대여",
    heart: 5,
  },
  {
    id: 3,
    mainImage: IMAGES.list3Iamge,
    title: "하루 2GB + 쾌속 무제한",
    price: "13,900원",
    salePrice: "67,000원",
    saleImage: IMAGES.saleIamge,
    mdImage: IMAGES.mdImage,
    name: "가짜거북이",
    info: "4G LTE 일 2GB 초과시, 5Mbps",
    rental: "일주일 단위 대여 가능",
    heart: 15,
  },
  {
    id: 4,
    mainImage: IMAGES.list4Iamge,
    title: "하루 4GB + 고속 무제한 평생소유",
    price: "104,900원",
    salePrice: "289,000원",
    saleImage: IMAGES.saleIamge,
    name: "모자장수 평생소유",
    info: "4G/LTE 일 4GB 초과 시, 5Mbps",
    rental: "기가 소유+데이터 1개월",
    heart: 9,
  },
  {
    id: 5,
    mainImage: IMAGES.list5Iamge,
    title: "속도저하 없는 고속 무제한",
    price: "54,900원",
    salePrice: "65,000원",
    saleImage: IMAGES.saleIamge,
    mdImage: IMAGES.bestImage,
    name: "하트여왕 MAX",
    info: "4G/LTE 최대 20Mbps",
    rental: "한 달 단위 대여",
    heart: 19,
  },
  {
    id: 6,
    mainImage: IMAGES.list6Iamge,
    title: "하루 2GB + 고속 무제한 ",
    price: "38,900원",
    salePrice: "65,000원",
    saleImage: IMAGES.saleIamge,
    name: "모자장수",
    info: "4G/LTE 일 2GB 초과 시, 4Mbps",
    rental: "한 달 단위 대여",
    heart: 15,
  },
  {
    id: 7,
    mainImage: IMAGES.list1Iamge,
    title: "한 달 20GB/40GB",
    price: "19,800원",
    salePrice: "48,000원",
    saleImage: IMAGES.saleIamge,
    name: "도마우스와 도도새",
    info: "4G/LTE",
    rental: "한 달 단위 대여",
    heart: 16,
  },
  {
    id: 8,
    mainImage: IMAGES.list8Iamge,
    title: "하루 1GB + 저속 무제한",
    price: "34,900원",
    salePrice: "55,000원",
    saleImage: IMAGES.saleIamge,
    name: "체셔고양이",
    info: "4G/LTE 일 1GB 초과 시, 1Mbps",
    rental: "한 달 단위 대여",
    heart: 3,
  },
  {
    id: 9,
    mainImage: IMAGES.list9Iamge,
    title: "하루 500MB + 저속 무제한",
    price: "28,900원",
    salePrice: "40,000원",
    saleImage: IMAGES.saleIamge,
    name: "흰토끼",
    info: "5Mbps 일 500MB 초과 시, 500Kbps",
    rental: "한 달 단위 대여",
    heart: 2,
  },
];
